### ISSUE TITLE
Pentaho version

### ISSUE THREAD

**Issue by fcorti** [Rospaccio/pentaho-authentication-ext#1]
Hi,
I suggest to write explicitly the Pentaho BA version supported in the documentation.
Did you see this?
http://pedroalves-bi.blogspot.it/2015/09/pentaho-60-ce-preview.html
Is it compliance with Pentaho 6 BA Server?

**Comment by Rospaccio** [comment]
Hi,
I tested the plugin with Pentaho 6.0 Preview and it works fine without any changes
